/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista.usuario;



import controlador.UsuarioDAO;
import modelo.Usuario;
import recursos.Recursos;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;



/**
 *
 * @author liza
 */
public class VentanaUsuarios extends javax.swing.JFrame {
    
    Recursos r;
    private Usuario u;
    private UsuarioDAO uDAO;

    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaUsuarios() {
        initComponents();
        setLocationRelativeTo(null);
    
        r = Recursos.getRecursos();
        u = new Usuario();
        uDAO = new UsuarioDAO();
        r.mostrarTabla(tbUsuarios, "SELECT Nombre,Administrador FROM Usuarios");
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jpPrincipal = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        panel = new javax.swing.JPanel();
        labelMetroICM1 = new com.icm.components.metro.LabelMetroICM();
        txtBuscar = new javax.swing.JTextField();
        labelMetroICM2 = new com.icm.components.metro.LabelMetroICM();
        txtClaveConf = new javax.swing.JPasswordField();
        labelMetroICM3 = new com.icm.components.metro.LabelMetroICM();
        ckAdmin = new com.icm.components.metro.CheckBoxMetroICM();
        labelMetroICM4 = new com.icm.components.metro.LabelMetroICM();
        txtClave = new javax.swing.JPasswordField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbUsuarios = new com.icm.components.metro.TableMetroICM();
        jSeparator1 = new javax.swing.JSeparator();
        labelMetroICM5 = new com.icm.components.metro.LabelMetroICM();
        txtNombre = new javax.swing.JTextField();
        btnNuevo = new com.icm.components.metro.ButtonMetroICM();
        btnEditar = new com.icm.components.metro.ButtonMetroICM();
        txtGuardar = new com.icm.components.metro.ButtonMetroICM();
        txtClear = new com.icm.components.metro.ButtonMetroICM();
        btnEliminar = new com.icm.components.metro.ButtonMetroICM();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Usuarios");
        setResizable(false);
        setSize(new java.awt.Dimension(860, 600));

        jpPrincipal.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(31, 189, 190));

        jPanel5.setBackground(new java.awt.Color(31, 189, 190));
        jPanel5.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 109, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 74, Short.MAX_VALUE)
        );

        jLabel2.setFont(new java.awt.Font("Verdana", 1, 36)); // NOI18N
        jLabel2.setForeground(java.awt.Color.white);
        jLabel2.setText("Usuarios");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(103, 103, 103)
                .addComponent(jLabel2)
                .addGap(199, 199, 199))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel2)
                .addContainerGap(24, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        panel.setBackground(java.awt.Color.white);
        panel.setPreferredSize(new java.awt.Dimension(661, 320));
        panel.setLayout(null);

        labelMetroICM1.setText("Confirmar contraseña:");
        panel.add(labelMetroICM1);
        labelMetroICM1.setBounds(30, 130, 140, 14);

        txtBuscar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        txtBuscar.setPreferredSize(new java.awt.Dimension(150, 38));
        txtBuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtBuscarKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBuscarKeyReleased(evt);
            }
        });
        panel.add(txtBuscar);
        txtBuscar.setBounds(230, 240, 210, 38);

        labelMetroICM2.setText("Nombre de usuario:");
        panel.add(labelMetroICM2);
        labelMetroICM2.setBounds(30, 30, 120, 14);

        txtClaveConf.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        txtClaveConf.setDisabledTextColor(new java.awt.Color(36, 36, 36));
        txtClaveConf.setEnabled(false);
        txtClaveConf.setPreferredSize(new java.awt.Dimension(102, 30));
        panel.add(txtClaveConf);
        txtClaveConf.setBounds(160, 120, 210, 40);

        labelMetroICM3.setText("Contraseña:");
        panel.add(labelMetroICM3);
        labelMetroICM3.setBounds(30, 80, 120, 14);

        ckAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ckAdminActionPerformed(evt);
            }
        });
        panel.add(ckAdmin);
        ckAdmin.setBounds(160, 170, 137, 25);

        labelMetroICM4.setText("Administrador:");
        panel.add(labelMetroICM4);
        labelMetroICM4.setBounds(30, 180, 85, 14);

        txtClave.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        txtClave.setDisabledTextColor(new java.awt.Color(36, 36, 36));
        txtClave.setEnabled(false);
        txtClave.setPreferredSize(new java.awt.Dimension(102, 30));
        panel.add(txtClave);
        txtClave.setBounds(160, 70, 210, 40);

        tbUsuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Nombre", "Administador"
            }
        ));
        tbUsuarios.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tbUsuariosFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tbUsuariosFocusLost(evt);
            }
        });
        tbUsuarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tbUsuariosMousePressed(evt);
            }
        });
        tbUsuarios.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tbUsuariosKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tbUsuariosKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(tbUsuarios);

        panel.add(jScrollPane1);
        jScrollPane1.setBounds(40, 290, 490, 170);

        jSeparator1.setForeground(new java.awt.Color(126, 56, 120));
        panel.add(jSeparator1);
        jSeparator1.setBounds(10, 220, 560, 6);

        labelMetroICM5.setText("Buscar usuario:");
        panel.add(labelMetroICM5);
        labelMetroICM5.setBounds(100, 250, 110, 14);

        txtNombre.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        txtNombre.setDisabledTextColor(new java.awt.Color(36, 36, 36));
        txtNombre.setEnabled(false);
        txtNombre.setPreferredSize(new java.awt.Dimension(150, 38));
        panel.add(txtNombre);
        txtNombre.setBounds(160, 20, 210, 38);

        btnNuevo.setBackground(new java.awt.Color(31, 189, 190));
        btnNuevo.setText("+ Nuevo");
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });
        panel.add(btnNuevo);
        btnNuevo.setBounds(410, 20, 130, 32);

        btnEditar.setBackground(new java.awt.Color(250, 104, 0));
        btnEditar.setText("Editar");
        btnEditar.setEnabled(false);
        btnEditar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnEditarMouseReleased(evt);
            }
        });
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });
        panel.add(btnEditar);
        btnEditar.setBounds(410, 70, 130, 32);

        txtGuardar.setText("Guardar");
        txtGuardar.setEnabled(false);
        txtGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGuardarActionPerformed(evt);
            }
        });
        panel.add(txtGuardar);
        txtGuardar.setBounds(410, 120, 130, 32);

        txtClear.setBackground(new java.awt.Color(96, 169, 23));
        txtClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtClearActionPerformed(evt);
            }
        });
        panel.add(txtClear);
        txtClear.setBounds(480, 170, 60, 32);

        btnEliminar.setBackground(new java.awt.Color(206, 53, 44));
        btnEliminar.setEnabled(false);
        btnEliminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnEliminarMouseReleased(evt);
            }
        });
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        panel.add(btnEliminar);
        btnEliminar.setBounds(410, 170, 60, 32);

        javax.swing.GroupLayout jpPrincipalLayout = new javax.swing.GroupLayout(jpPrincipal);
        jpPrincipal.setLayout(jpPrincipalLayout);
        jpPrincipalLayout.setHorizontalGroup(
            jpPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(panel, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        jpPrincipalLayout.setVerticalGroup(
            jpPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpPrincipalLayout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, 492, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ckAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ckAdminActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ckAdminActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
        // TODO add your handling code here:
        r.habilitarComponentes(true, txtNombre,txtClave,txtClaveConf,txtGuardar);
        r.limpiar(txtNombre,txtClave,txtClaveConf,txtBuscar);
        ckAdmin.setSelected(false);
        tbUsuarios.clearSelection();
    }//GEN-LAST:event_btnNuevoActionPerformed

    private void txtGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGuardarActionPerformed
        // TODO add your handling code here:
        if (r.componentesVacios(txtNombre, txtClave, txtClaveConf)) {
            r.mostrarNotificacionError("Falta informacion", "Debes ingresar todos los datos del usuario...");
        } else {

            if (txtClave.getText().equals(txtClaveConf.getText())) {
                u.setUsuario(txtNombre.getText());
                u.setIsAdmin(ckAdmin.isSelected());
                u.setContraseña(txtClaveConf.getText());

                try {
                    if (uDAO.consultaAlumno(u.getUsuario()) != null) {
                        r.mostrarNotificacionCuidado("Usuario no registrado", "El usuario ya se encuentra registrado.");
                    } else {
                        if (uDAO.registrarUsuario(u)) {
                            r.mostrarNotificacionExito("Operacion exitosa !!!", "Usuario registrado con exito.");
                            r.mostrarTabla(tbUsuarios, "SELECT Nombre,Administrador FROM Usuarios");
                            r.limpiar(txtNombre, txtClave, txtClaveConf, txtBuscar);
                            ckAdmin.setSelected(false);
                            tbUsuarios.clearSelection();
                            r.habilitarComponentes(false, txtNombre, txtClave, txtClaveConf, txtGuardar, txtBuscar);
                            r.limpiar(txtNombre, txtClave, txtClaveConf);
                            ckAdmin.setSelected(false);
                            tbUsuarios.clearSelection();
                        } else {
                            r.mostrarNotificacionError("Error al registrar usuario ", "No se pudo registrar al usuario.");
                        }
                    }
                } catch (Exception ex) {
                    Logger.getLogger(VentanaUsuarios.class.getName()).log(Level.SEVERE, null, ex);
                }

            } else {
                r.mostrarNotificacionError("Contaseña incorrecta ", "La contaseña de confirmacion no coincide");
            }

        }
    }//GEN-LAST:event_txtGuardarActionPerformed

    private void txtBuscarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscarKeyPressed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_txtBuscarKeyPressed

    private void txtBuscarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscarKeyReleased
        // TODO add your handling code here:
         r.mostrarTabla(tbUsuarios, "SELECT Nombre,Administrador FROM Usuarios WHERE Nombre LIKE '"+txtBuscar.getText()+"%'");
    }//GEN-LAST:event_txtBuscarKeyReleased

    private void tbUsuariosKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tbUsuariosKeyReleased
        // TODO add your handling code here:
        txtNombre.setText(String.valueOf(tbUsuarios.getValueAt(tbUsuarios.getSelectedRow(),0)));
        try {
            u = uDAO.consultaAlumno(txtNombre.getText());
        } catch (Exception ex) {
            Logger.getLogger(VentanaUsuarios.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        txtClave.setText(u.getContraseña());
        txtClaveConf.setText(u.getContraseña());
        ckAdmin.setSelected(u.isIsAdmin());
        
         r.habilitarComponentes(false, txtNombre, txtClave, txtClaveConf);
    }//GEN-LAST:event_tbUsuariosKeyReleased

    private void tbUsuariosKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tbUsuariosKeyPressed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_tbUsuariosKeyPressed

    private void tbUsuariosMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbUsuariosMousePressed
        // TODO add your handling code here:
         txtNombre.setText(String.valueOf(tbUsuarios.getValueAt(tbUsuarios.getSelectedRow(),0)));
        try {
            u = uDAO.consultaAlumno(txtNombre.getText());
        } catch (Exception ex) {
            Logger.getLogger(VentanaUsuarios.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        txtClave.setText(u.getContraseña());
        txtClaveConf.setText(u.getContraseña());
        ckAdmin.setSelected(u.isIsAdmin());
        
         r.habilitarComponentes(false, txtNombre, txtClave, txtClaveConf);
        
    }//GEN-LAST:event_tbUsuariosMousePressed

    private void tbUsuariosFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tbUsuariosFocusGained
        // TODO add your handling code here:
        btnEditar.setEnabled(true);
        btnEliminar.setEnabled(true);
    }//GEN-LAST:event_tbUsuariosFocusGained

    private void tbUsuariosFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tbUsuariosFocusLost
        // TODO add your handling code here:
          btnEditar.setEnabled(false);
           btnEliminar.setEnabled(false);
    }//GEN-LAST:event_tbUsuariosFocusLost

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnEditarMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditarMouseReleased
        // TODO add your handling code here:
         r.habilitarComponentes(true, txtNombre, txtClave, txtClaveConf,txtGuardar);
         btnNuevo.setEnabled(false);
    }//GEN-LAST:event_btnEditarMouseReleased

    private void btnEliminarMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEliminarMouseReleased
        // TODO add your handling code here:
        if(JOptionPane.showConfirmDialog(this, "Esta seguro de eliminar al usuario ?") == 0){
           if(uDAO.eliminarUsuario(txtNombre.getText())){
               r.mostrarNotificacionExito("Usuario elimnado", "El usuario ha sido eliminado con exito...");
               r.mostrarTabla(tbUsuarios, "SELECT Nombre,Administrador FROM Usuarios");
               r.limpiar(txtNombre, txtClave, txtClaveConf);
               ckAdmin.setSelected(false);
               
               
           }else{
               r.mostrarNotificacionError("No se puedo eliminar el usuario", "Ocurrio un error al intentar eliminar el usuario...");
           }
        }
    }//GEN-LAST:event_btnEliminarMouseReleased

    private void txtClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtClearActionPerformed
        // TODO add your handling code here:
        r.habilitarComponentes(false, txtNombre, txtClave, txtClaveConf,txtGuardar,txtBuscar);
        r.limpiar(txtNombre, txtClave, txtClaveConf);
        ckAdmin.setSelected(false);
        tbUsuarios.clearSelection();
    }//GEN-LAST:event_txtClearActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
 /*
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaUsuarios().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.icm.components.metro.ButtonMetroICM btnEditar;
    private com.icm.components.metro.ButtonMetroICM btnEliminar;
    private com.icm.components.metro.ButtonMetroICM btnNuevo;
    private javax.swing.ButtonGroup buttonGroup1;
    private com.icm.components.metro.CheckBoxMetroICM ckAdmin;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPanel jpPrincipal;
    private com.icm.components.metro.LabelMetroICM labelMetroICM1;
    private com.icm.components.metro.LabelMetroICM labelMetroICM2;
    private com.icm.components.metro.LabelMetroICM labelMetroICM3;
    private com.icm.components.metro.LabelMetroICM labelMetroICM4;
    private com.icm.components.metro.LabelMetroICM labelMetroICM5;
    private javax.swing.JPanel panel;
    private com.icm.components.metro.TableMetroICM tbUsuarios;
    private javax.swing.JTextField txtBuscar;
    private javax.swing.JPasswordField txtClave;
    private javax.swing.JPasswordField txtClaveConf;
    private com.icm.components.metro.ButtonMetroICM txtClear;
    private com.icm.components.metro.ButtonMetroICM txtGuardar;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
