/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista.clientes;

import modelo.Cliente;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author liza
 */
public class VentanaClientesBajas extends javax.swing.JFrame implements VariablesCliente {

    private Cliente c;

    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaClientesBajas() {
        initComponents();
        setLocationRelativeTo(null);
        c = new Cliente();
        r.mostrarTabla(tbClienteBajas, "SELECT * FROM Clientes");
        r.ordenTabulacion(txtClienteCurp, txtClienteNombre, txtClientePrimerAp,
                txtClienteSegundoAp, txtClienteDireccion, txtClienteTelefono,
                txtClienteNegocio, btnClienteEliminar, btnCleinteLimpiar, btnClienteCancelar);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtClienteCurp = new com.icm.components.metro.TextFieldMetroICM();
        txtClienteNombre = new com.icm.components.metro.TextFieldMetroICM();
        txtClienteSegundoAp = new com.icm.components.metro.TextFieldMetroICM();
        txtClientePrimerAp = new com.icm.components.metro.TextFieldMetroICM();
        txtClienteNegocio = new com.icm.components.metro.TextFieldMetroICM();
        txtClienteTelefono = new com.icm.components.metro.TextFieldMetroICM();
        txtClienteDireccion = new com.icm.components.metro.TextFieldMetroICM();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        btnClienteBuscar = new com.icm.components.metro.ButtonMetroICM();
        btnCleinteLimpiar = new com.icm.components.metro.ButtonMetroICM();
        btnClienteCancelar = new com.icm.components.metro.ButtonMetroICM();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbClienteBajas = new com.icm.components.metro.TableMetroICM();
        jPanel3 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        btnClienteEliminar = new com.icm.components.metro.ButtonMetroICM();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Clientes Bajas");
        setSize(new java.awt.Dimension(860, 600));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(31, 189, 190));

        jPanel4.setBackground(new java.awt.Color(31, 189, 190));
        jPanel4.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        jLabel2.setFont(new java.awt.Font("Verdana", 1, 36)); // NOI18N
        jLabel2.setForeground(java.awt.Color.white);
        jLabel2.setText("Clientes Bajas");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 295, Short.MAX_VALUE)
                .addGap(209, 209, 209))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel2)
                .addContainerGap(39, Short.MAX_VALUE))
        );

        jPanel5.setBackground(new java.awt.Color(31, 189, 190));
        jPanel5.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 237, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(53, 53, 53)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel1.setText("Ingresa los siguientes datos:");

        jLabel3.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel3.setText("ID:");

        txtClienteCurp.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(216, 0, 115)));
        txtClienteCurp.setForeground(java.awt.Color.black);
        txtClienteCurp.setDark(false);
        txtClienteCurp.setDisabledTextColor(java.awt.Color.darkGray);
        txtClienteCurp.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        txtClienteCurp.setMargin(new java.awt.Insets(0, 0, 0, 0));
        txtClienteCurp.setName(""); // NOI18N
        txtClienteCurp.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtClienteCurpKeyReleased(evt);
            }
        });

        txtClienteNombre.setEditable(false);
        txtClienteNombre.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(216, 0, 115)));
        txtClienteNombre.setForeground(java.awt.Color.black);
        txtClienteNombre.setDisabledTextColor(java.awt.Color.darkGray);
        txtClienteNombre.setEnabled(false);
        txtClienteNombre.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N

        txtClienteSegundoAp.setEditable(false);
        txtClienteSegundoAp.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(216, 0, 115)));
        txtClienteSegundoAp.setForeground(java.awt.Color.black);
        txtClienteSegundoAp.setDisabledTextColor(java.awt.Color.darkGray);
        txtClienteSegundoAp.setEnabled(false);
        txtClienteSegundoAp.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N

        txtClientePrimerAp.setEditable(false);
        txtClientePrimerAp.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(216, 0, 115)));
        txtClientePrimerAp.setForeground(java.awt.Color.black);
        txtClientePrimerAp.setDisabledTextColor(java.awt.Color.darkGray);
        txtClientePrimerAp.setEnabled(false);
        txtClientePrimerAp.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N

        txtClienteNegocio.setEditable(false);
        txtClienteNegocio.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(216, 0, 115)));
        txtClienteNegocio.setForeground(java.awt.Color.black);
        txtClienteNegocio.setDisabledTextColor(java.awt.Color.darkGray);
        txtClienteNegocio.setEnabled(false);
        txtClienteNegocio.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N

        txtClienteTelefono.setEditable(false);
        txtClienteTelefono.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(216, 0, 115)));
        txtClienteTelefono.setForeground(java.awt.Color.black);
        txtClienteTelefono.setDisabledTextColor(java.awt.Color.darkGray);
        txtClienteTelefono.setEnabled(false);
        txtClienteTelefono.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N

        txtClienteDireccion.setEditable(false);
        txtClienteDireccion.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(216, 0, 115)));
        txtClienteDireccion.setForeground(java.awt.Color.black);
        txtClienteDireccion.setDisabledTextColor(java.awt.Color.darkGray);
        txtClienteDireccion.setEnabled(false);
        txtClienteDireccion.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel4.setText("Nombre:");

        jLabel5.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel5.setText("Primer apellido:");

        jLabel6.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel6.setText("Segundo apellido:");

        jLabel7.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel7.setText("Dirección :");

        jLabel8.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel8.setText("Teléfono:");

        jLabel9.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel9.setText("Nombre negocio:");

        btnClienteBuscar.setText("Buscar");
        btnClienteBuscar.setEnabled(false);
        btnClienteBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClienteBuscarActionPerformed(evt);
            }
        });

        btnCleinteLimpiar.setBackground(new java.awt.Color(96, 169, 23));
        btnCleinteLimpiar.setText("Limpiar");
        btnCleinteLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCleinteLimpiarActionPerformed(evt);
            }
        });

        btnClienteCancelar.setBackground(new java.awt.Color(206, 53, 44));
        btnClienteCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/estetica/maty/iconos/boton_cancelar.png"))); // NOI18N
        btnClienteCancelar.setText("Cancelar");

        tbClienteBajas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tbClienteBajas);

        jPanel3.setBackground(java.awt.Color.white);

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/Eliminar.png"))); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(jLabel10)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addComponent(jLabel10)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel11.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel11.setText("Clientes:");

        btnClienteEliminar.setBackground(new java.awt.Color(250, 104, 0));
        btnClienteEliminar.setText("Eliminar");
        btnClienteEliminar.setEnabled(false);
        btnClienteEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClienteEliminarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(35, 35, 35)
                                .addComponent(jLabel1)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtClienteNegocio, javax.swing.GroupLayout.DEFAULT_SIZE, 205, Short.MAX_VALUE)
                            .addComponent(txtClienteTelefono, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtClienteDireccion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtClienteSegundoAp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtClientePrimerAp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtClienteNombre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtClienteCurp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(66, 66, 66)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnClienteBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnCleinteLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnClienteCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnClienteEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(69, 69, 69))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtClienteCurp, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(btnClienteBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtClienteNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtClientePrimerAp, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtClienteSegundoAp, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtClienteDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtClienteTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel8))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtClienteNegocio, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel9)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(btnClienteEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(46, 46, 46)
                                .addComponent(btnCleinteLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(56, 56, 56)
                                .addComponent(btnClienteCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18))))
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnClienteBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClienteBuscarActionPerformed
        // TODO add your handling code here:
        if (r.componentesVacios(txtClienteCurp)) {
            r.mostrarNotificacionError("Error", "Debes ingresar todos los datos del cliente...");
        } else {
            c = cDAO.consultaCliente(txtClienteCurp.getText().toUpperCase());

            if (c == null) {
                r.mostrarNotificacionInfo("Cliente no encontrado !!!", "Al parecer el cliente no esta registrado en la base de datos.");
            } else {
                txtClienteNombre.setText(c.getNombre());
                txtClientePrimerAp.setText(c.getPrimerAp());
                txtClienteSegundoAp.setText(c.getSegundoAp());
                txtClienteDireccion.setText(c.getDireccion());
                txtClienteTelefono.setText(c.getTelefono());
                txtClienteNegocio.setText(c.getNegocio());
                btnClienteEliminar.setEnabled(true);
                r.mostrarNotificacionExito("Cliente encontrado", "Se ha encontrado el cliente " + txtClienteNombre.getText() + " registrado en la base de datos.");
                r.mostrarTabla(tbClienteBajas, "SELECT * FROM Clientes WHERE Curp = '" + txtClienteCurp.getText().toUpperCase() + "'");
            }
        }

    }//GEN-LAST:event_btnClienteBuscarActionPerformed

    private void txtClienteCurpKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtClienteCurpKeyReleased
        // TODO add your handling code here:
        if (r.componentesVacios(txtClienteCurp)) {
            btnClienteBuscar.setEnabled(false);
        } else {
            btnClienteBuscar.setEnabled(true);
        }
    }//GEN-LAST:event_txtClienteCurpKeyReleased

    private void btnClienteEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClienteEliminarActionPerformed
        // TODO add your handling code here:
        if (JOptionPane.showConfirmDialog(this, "Esta realmente seguro de eliminar el cliente " + txtClienteNombre.getText() + "?") == 0) {

            if (cDAO.eliminarClinete(txtClienteCurp.getText())) {
                r.mostrarNotificacionInfo("Cliente Eliminado !!!", "Se ha eliminado el cliente " + txtClienteNombre.getText() + " de la base de datos.");
                btnClienteEliminar.setEnabled(false);
                btnClienteBuscar.setEnabled(false);
                r.mostrarTabla(tbClienteBajas, "SELECT * FROM Clientes");
                r.limpiar(txtClienteCurp, txtClienteNombre, txtClientePrimerAp,
                        txtClienteSegundoAp, txtClienteDireccion, txtClienteTelefono,
                        txtClienteNegocio);
                 txtClienteCurp.requestFocus();
            }

        }
    }//GEN-LAST:event_btnClienteEliminarActionPerformed

    private void btnCleinteLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCleinteLimpiarActionPerformed
        // TODO add your handling code here:
         r.limpiar(txtClienteCurp, txtClienteNombre, txtClientePrimerAp,
                        txtClienteSegundoAp, txtClienteDireccion, txtClienteTelefono,
                        txtClienteNegocio);
         btnClienteEliminar.setEnabled(false);
         btnClienteBuscar.setEnabled(false);
         txtClienteCurp.requestFocus();
    }//GEN-LAST:event_btnCleinteLimpiarActionPerformed

    public void setColor(JPanel panel) {
        panel.setBackground(new java.awt.Color(197, 197, 197));
    }

    public void resetColor(JPanel panel) {
        panel.setBackground(new java.awt.Color(223, 223, 223));
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
 /*
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaClientesBajas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.icm.components.metro.ButtonMetroICM btnCleinteLimpiar;
    private com.icm.components.metro.ButtonMetroICM btnClienteBuscar;
    private com.icm.components.metro.ButtonMetroICM btnClienteCancelar;
    private com.icm.components.metro.ButtonMetroICM btnClienteEliminar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private com.icm.components.metro.TableMetroICM tbClienteBajas;
    private com.icm.components.metro.TextFieldMetroICM txtClienteCurp;
    private com.icm.components.metro.TextFieldMetroICM txtClienteDireccion;
    private com.icm.components.metro.TextFieldMetroICM txtClienteNegocio;
    private com.icm.components.metro.TextFieldMetroICM txtClienteNombre;
    private com.icm.components.metro.TextFieldMetroICM txtClientePrimerAp;
    private com.icm.components.metro.TextFieldMetroICM txtClienteSegundoAp;
    private com.icm.components.metro.TextFieldMetroICM txtClienteTelefono;
    // End of variables declaration//GEN-END:variables
}
