/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista.clientes;

import static vista.clientes.VariablesCliente.r;
import javax.swing.JPanel;

/**
 *
 * @author liza
 */
public class VentanaClientesConsultas extends javax.swing.JFrame {

    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaClientesConsultas() {
        initComponents();
        setLocationRelativeTo(null);
        r.mostrarTabla(tbClienteCnsultas, "SELECT * FROM Clientes");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jpPrincipal = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtClienteCurp = new com.icm.components.metro.TextFieldMetroICM();
        txtClienteNombre = new com.icm.components.metro.TextFieldMetroICM();
        txtClienteSegundoAp = new com.icm.components.metro.TextFieldMetroICM();
        txtClientePrimerAp = new com.icm.components.metro.TextFieldMetroICM();
        txtClienteNegocio = new com.icm.components.metro.TextFieldMetroICM();
        txtClienteTelefono = new com.icm.components.metro.TextFieldMetroICM();
        txtClienteDireccion = new com.icm.components.metro.TextFieldMetroICM();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        btnClienteBuscar = new com.icm.components.metro.ButtonMetroICM();
        btnCleinteLimpiar = new com.icm.components.metro.ButtonMetroICM();
        btnClienteCancelar = new com.icm.components.metro.ButtonMetroICM();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbClienteCnsultas = new com.icm.components.metro.TableMetroICM();
        jPanel3 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        rbCurp = new com.icm.components.metro.RadioButtonMetroICM();
        rbNombre = new com.icm.components.metro.RadioButtonMetroICM();
        rbPrimerAp = new com.icm.components.metro.RadioButtonMetroICM();
        rbSegundoAp = new com.icm.components.metro.RadioButtonMetroICM();
        rbDireccion = new com.icm.components.metro.RadioButtonMetroICM();
        rbTelefono = new com.icm.components.metro.RadioButtonMetroICM();
        rbNegocio = new com.icm.components.metro.RadioButtonMetroICM();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Clientes Consultas");
        setSize(new java.awt.Dimension(860, 600));

        jpPrincipal.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(31, 189, 190));

        jPanel4.setBackground(new java.awt.Color(31, 189, 190));
        jPanel4.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 221, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 104, Short.MAX_VALUE)
        );

        jPanel5.setBackground(new java.awt.Color(31, 189, 190));
        jPanel5.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 109, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jLabel2.setFont(new java.awt.Font("Verdana", 1, 36)); // NOI18N
        jLabel2.setForeground(java.awt.Color.white);
        jLabel2.setText("Clientes Consultas");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(144, 144, 144)
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel1.setText("Ingresa los siguientes datos:");

        jLabel3.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel3.setText("ID::");

        txtClienteCurp.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(216, 0, 115)));
        txtClienteCurp.setToolTipText("");
        txtClienteCurp.setDark(false);
        txtClienteCurp.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        txtClienteCurp.setMaximumSize(new java.awt.Dimension(300, 48));
        txtClienteCurp.setNextFocusableComponent(txtClienteNombre);
        txtClienteCurp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtClienteCurpActionPerformed(evt);
            }
        });
        txtClienteCurp.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtClienteCurpKeyReleased(evt);
            }
        });

        txtClienteNombre.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(216, 0, 115)));
        txtClienteNombre.setMaximumSize(new java.awt.Dimension(300, 48));
        txtClienteNombre.setNextFocusableComponent(txtClientePrimerAp);
        txtClienteNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtClienteNombreKeyReleased(evt);
            }
        });

        txtClienteSegundoAp.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(216, 0, 115)));
        txtClienteSegundoAp.setMaximumSize(new java.awt.Dimension(300, 48));
        txtClienteSegundoAp.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtClienteSegundoApKeyReleased(evt);
            }
        });

        txtClientePrimerAp.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(216, 0, 115)));
        txtClientePrimerAp.setMaximumSize(new java.awt.Dimension(300, 48));
        txtClientePrimerAp.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtClientePrimerApKeyReleased(evt);
            }
        });

        txtClienteNegocio.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(216, 0, 115)));
        txtClienteNegocio.setMaximumSize(new java.awt.Dimension(300, 48));
        txtClienteNegocio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtClienteNegocioKeyReleased(evt);
            }
        });

        txtClienteTelefono.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(216, 0, 115)));
        txtClienteTelefono.setMaximumSize(new java.awt.Dimension(300, 48));
        txtClienteTelefono.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtClienteTelefonoKeyReleased(evt);
            }
        });

        txtClienteDireccion.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(216, 0, 115)));
        txtClienteDireccion.setMaximumSize(new java.awt.Dimension(300, 48));
        txtClienteDireccion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtClienteDireccionKeyReleased(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel4.setText("Nombre:");

        jLabel5.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel5.setText("Primer apellido:");

        jLabel6.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel6.setText("Segundo apellido:");

        jLabel7.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel7.setText("Dirección :");

        jLabel8.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel8.setText("Teléfono:");

        jLabel9.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel9.setText("Nombre negocio:");

        btnClienteBuscar.setBackground(new java.awt.Color(31, 189, 190));
        btnClienteBuscar.setText("Buscar");
        btnClienteBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClienteBuscarActionPerformed(evt);
            }
        });

        btnCleinteLimpiar.setBackground(new java.awt.Color(96, 169, 23));
        btnCleinteLimpiar.setText("Limpiar");
        btnCleinteLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCleinteLimpiarActionPerformed(evt);
            }
        });

        btnClienteCancelar.setBackground(new java.awt.Color(206, 53, 44));
        btnClienteCancelar.setText("Cancelar");
        btnClienteCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClienteCancelarActionPerformed(evt);
            }
        });

        tbClienteCnsultas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tbClienteCnsultas);

        jPanel3.setBackground(java.awt.Color.white);

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/BUscar.png"))); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(37, Short.MAX_VALUE)
                .addComponent(jLabel10)
                .addGap(35, 35, 35))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addComponent(jLabel10)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel11.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel11.setText("Clientes:");

        buttonGroup1.add(rbCurp);
        rbCurp.setDark(false);
        rbCurp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbCurpActionPerformed(evt);
            }
        });

        buttonGroup1.add(rbNombre);
        rbNombre.setDark(false);
        rbNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbNombreActionPerformed(evt);
            }
        });

        buttonGroup1.add(rbPrimerAp);
        rbPrimerAp.setDark(false);
        rbPrimerAp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbPrimerApActionPerformed(evt);
            }
        });
        rbPrimerAp.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                rbPrimerApKeyReleased(evt);
            }
        });

        buttonGroup1.add(rbSegundoAp);
        rbSegundoAp.setDark(false);
        rbSegundoAp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbSegundoApActionPerformed(evt);
            }
        });
        rbSegundoAp.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                rbSegundoApKeyReleased(evt);
            }
        });

        buttonGroup1.add(rbDireccion);
        rbDireccion.setDark(false);
        rbDireccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbDireccionActionPerformed(evt);
            }
        });

        buttonGroup1.add(rbTelefono);
        rbTelefono.setDark(false);
        rbTelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbTelefonoActionPerformed(evt);
            }
        });

        buttonGroup1.add(rbNegocio);
        rbNegocio.setDark(false);
        rbNegocio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbNegocioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpPrincipalLayout = new javax.swing.GroupLayout(jpPrincipal);
        jpPrincipal.setLayout(jpPrincipalLayout);
        jpPrincipalLayout.setHorizontalGroup(
            jpPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jpPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpPrincipalLayout.createSequentialGroup()
                        .addGroup(jpPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpPrincipalLayout.createSequentialGroup()
                                .addGap(35, 35, 35)
                                .addComponent(jLabel1))
                            .addGroup(jpPrincipalLayout.createSequentialGroup()
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jpPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(rbCurp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(rbNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(rbPrimerAp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(rbSegundoAp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(rbDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(rbTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(rbNegocio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(18, 18, 18)
                        .addGroup(jpPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addGroup(jpPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel5)))
                        .addGap(18, 18, 18)
                        .addGroup(jpPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtClienteNegocio, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                            .addComponent(txtClienteTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                            .addComponent(txtClienteDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                            .addComponent(txtClienteSegundoAp, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                            .addComponent(txtClientePrimerAp, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                            .addComponent(txtClienteNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                            .addComponent(txtClienteCurp, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE))
                        .addGap(64, 64, 64)
                        .addGroup(jpPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnClienteBuscar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnCleinteLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnClienteCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(71, 71, 71))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpPrincipalLayout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addContainerGap())))
            .addGroup(jpPrincipalLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel11)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jpPrincipalLayout.setVerticalGroup(
            jpPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpPrincipalLayout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpPrincipalLayout.createSequentialGroup()
                        .addGroup(jpPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtClienteCurp, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel3))
                            .addComponent(rbCurp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jpPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpPrincipalLayout.createSequentialGroup()
                                .addGroup(jpPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jpPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(txtClienteNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel4))
                                    .addComponent(rbNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jpPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jpPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(txtClientePrimerAp, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel5))
                                    .addComponent(rbPrimerAp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jpPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jpPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(txtClienteSegundoAp, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel6))
                                    .addComponent(rbSegundoAp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jpPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jpPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(txtClienteDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel7))
                                    .addComponent(rbDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jpPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(rbTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jpPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(txtClienteTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel8))))
                            .addGroup(jpPrincipalLayout.createSequentialGroup()
                                .addComponent(btnClienteBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(56, 56, 56)
                                .addComponent(btnCleinteLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(56, 56, 56)
                                .addComponent(btnClienteCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jpPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rbNegocio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jpPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtClienteNegocio, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel9))))
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(1, 1, 1)
                .addComponent(jLabel11)
                .addGap(2, 2, 2)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 195, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rbCurpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbCurpActionPerformed
        // TODO add your handling code here:
        r.seleccionRBBuscar(txtClienteCurp, txtClienteNombre, txtClientePrimerAp,
                txtClienteSegundoAp, txtClienteDireccion, txtClienteTelefono,
                txtClienteNegocio);
    }//GEN-LAST:event_rbCurpActionPerformed

    private void rbNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbNombreActionPerformed
        // TODO add your handling code here:
        r.seleccionRBBuscar(txtClienteNombre, txtClienteCurp, txtClientePrimerAp,
                txtClienteSegundoAp, txtClienteDireccion, txtClienteTelefono,
                txtClienteNegocio);
    }//GEN-LAST:event_rbNombreActionPerformed

    private void rbPrimerApActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbPrimerApActionPerformed
        // TODO add your handling code here:
        r.seleccionRBBuscar(txtClientePrimerAp, txtClienteNombre, txtClienteCurp,
                txtClienteSegundoAp, txtClienteDireccion, txtClienteTelefono,
                txtClienteNegocio);
    }//GEN-LAST:event_rbPrimerApActionPerformed

    private void rbSegundoApActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbSegundoApActionPerformed
        // TODO add your handling code here:
        r.seleccionRBBuscar(txtClienteSegundoAp, txtClientePrimerAp, txtClienteNombre, txtClienteCurp,
                txtClienteDireccion, txtClienteTelefono,
                txtClienteNegocio);
    }//GEN-LAST:event_rbSegundoApActionPerformed

    private void rbDireccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbDireccionActionPerformed
        // TODO add your handling code here:
        r.seleccionRBBuscar(txtClienteDireccion, txtClienteSegundoAp, txtClientePrimerAp, txtClienteNombre, txtClienteCurp,
                txtClienteTelefono,
                txtClienteNegocio);
    }//GEN-LAST:event_rbDireccionActionPerformed

    private void rbTelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbTelefonoActionPerformed
        // TODO add your handling code here:
        r.seleccionRBBuscar(txtClienteTelefono, txtClienteDireccion, txtClienteSegundoAp, txtClientePrimerAp, txtClienteNombre, txtClienteCurp,
                txtClienteNegocio);
    }//GEN-LAST:event_rbTelefonoActionPerformed

    private void rbNegocioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbNegocioActionPerformed
        // TODO add your handling code here:
        r.seleccionRBBuscar(txtClienteNegocio, txtClienteTelefono, txtClienteDireccion, txtClienteSegundoAp, txtClientePrimerAp, txtClienteNombre, txtClienteCurp);
    }//GEN-LAST:event_rbNegocioActionPerformed

    private void txtClienteCurpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtClienteCurpActionPerformed
        // TODO add your handling code here:
        r.mostrarTabla(tbClienteCnsultas, "SELECT * FROM Clientes WHERE Curp LIKE '" + txtClienteCurp.getText().toUpperCase() + "%'");
    }//GEN-LAST:event_txtClienteCurpActionPerformed

    private void txtClienteCurpKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtClienteCurpKeyReleased
        // TODO add your handling code here:
        r.mostrarTabla(tbClienteCnsultas, "SELECT * FROM Clientes WHERE Curp LIKE '" + txtClienteCurp.getText().toUpperCase() + "%'");
    }//GEN-LAST:event_txtClienteCurpKeyReleased

    private void txtClienteNombreKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtClienteNombreKeyReleased
        // TODO add your handling code here:
        r.mostrarTabla(tbClienteCnsultas, "SELECT * FROM Clientes WHERE Nombre LIKE '" + txtClienteNombre.getText() + "%'");
    }//GEN-LAST:event_txtClienteNombreKeyReleased

    private void rbPrimerApKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_rbPrimerApKeyReleased
        // TODO add your handling code here:

    }//GEN-LAST:event_rbPrimerApKeyReleased

    private void rbSegundoApKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_rbSegundoApKeyReleased
        // TODO add your handling code here:

    }//GEN-LAST:event_rbSegundoApKeyReleased

    private void txtClienteDireccionKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtClienteDireccionKeyReleased
        // TODO add your handling code here:
        r.mostrarTabla(tbClienteCnsultas, "SELECT * FROM Clientes WHERE Direccion LIKE '" + txtClienteDireccion.getText() + "%'");
    }//GEN-LAST:event_txtClienteDireccionKeyReleased

    private void txtClienteSegundoApKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtClienteSegundoApKeyReleased
        // TODO add your handling code here:
        r.mostrarTabla(tbClienteCnsultas, "SELECT * FROM Clientes WHERE Segundo_Ap LIKE '" + txtClienteSegundoAp.getText() + "%'");
    }//GEN-LAST:event_txtClienteSegundoApKeyReleased

    private void txtClienteTelefonoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtClienteTelefonoKeyReleased
        // TODO add your handling code here:
        r.mostrarTabla(tbClienteCnsultas, "SELECT * FROM Clientes WHERE Telefono LIKE '" + txtClienteTelefono.getText() + "%'");
    }//GEN-LAST:event_txtClienteTelefonoKeyReleased

    private void txtClienteNegocioKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtClienteNegocioKeyReleased
        // TODO add your handling code here:
        r.mostrarTabla(tbClienteCnsultas, "SELECT * FROM Clientes WHERE Negocio LIKE '" + txtClienteNegocio.getText() + "%'");
    }//GEN-LAST:event_txtClienteNegocioKeyReleased

    private void txtClientePrimerApKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtClientePrimerApKeyReleased
        // TODO add your handling code here:
        r.mostrarTabla(tbClienteCnsultas, "SELECT * FROM Clientes WHERE Primer_Ap LIKE '" + txtClientePrimerAp.getText() + "%'");
    }//GEN-LAST:event_txtClientePrimerApKeyReleased

    private void btnClienteCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClienteCancelarActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnClienteCancelarActionPerformed

    private void btnCleinteLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCleinteLimpiarActionPerformed
        // TODO add your handling code here:
        r.limpiar(txtClienteCurp, txtClienteNombre, txtClientePrimerAp,
                txtClienteSegundoAp, txtClienteDireccion, txtClienteTelefono,
                txtClienteNegocio);
    }//GEN-LAST:event_btnCleinteLimpiarActionPerformed

    private void btnClienteBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClienteBuscarActionPerformed
        // TODO add your handling code here:
        if (rbCurp.isSelected()) {
            if (r.componentesVacios(txtClienteCurp)) {
                r.mostrarNotificacionCuidado("Ne se pudo obtener ningun resultado", "Dbes ingresar datos al campo seleccionado para buscar al cliente....");
            } else {
                r.mostrarTabla(tbClienteCnsultas, "SELECT * FROM Clientes WHERE Curp LIKE '" + txtClienteCurp.getText().toUpperCase() + "%'");
            }
        } else if (rbNombre.isSelected()) {
            if (r.componentesVacios(txtClienteNombre)) {
                r.mostrarNotificacionCuidado("Ne se pudo obtener ningun resultado", "Dbes ingresar datos al campo seleccionado para buscar al cliente....");
            } else {
                r.mostrarTabla(tbClienteCnsultas, "SELECT * FROM Clientes WHERE Nombre LIKE '" + txtClienteNombre.getText() + "%'");
            }
        } else if (rbPrimerAp.isSelected()) {
            if (r.componentesVacios(txtClientePrimerAp)) {
                r.mostrarNotificacionCuidado("Ne se pudo obtener ningun resultado", "Dbes ingresar datos al campo seleccionado para buscar al cliente....");
            } else {
                r.mostrarTabla(tbClienteCnsultas, "SELECT * FROM Clientes WHERE Primer_Ap LIKE '" + txtClientePrimerAp.getText() + "%'");

            }
        } else if (rbSegundoAp.isSelected()) {
            if (r.componentesVacios(txtClienteSegundoAp)) {
                r.mostrarNotificacionCuidado("Ne se pudo obtener ningun resultado", "Dbes ingresar datos al campo seleccionado para buscar al cliente....");
            } else {
                r.mostrarTabla(tbClienteCnsultas, "SELECT * FROM Clientes WHERE Segundo_Ap LIKE '" + txtClienteSegundoAp.getText() + "%'");
            }
        } else if (rbDireccion.isSelected()) {
            if (r.componentesVacios(txtClienteDireccion)) {
                r.mostrarNotificacionCuidado("Ne se pudo obtener ningun resultado", "Dbes ingresar datos al campo seleccionado para buscar al cliente....");
            } else {
                r.mostrarTabla(tbClienteCnsultas, "SELECT * FROM Clientes WHERE Direccion LIKE '" + txtClienteDireccion.getText() + "%'");
            }
        } else if (rbTelefono.isSelected()) {
            if (r.componentesVacios(txtClienteTelefono)) {
                r.mostrarNotificacionCuidado("Ne se pudo obtener ningun resultado", "Dbes ingresar datos al campo seleccionado para buscar al cliente....");
            } else {
                r.mostrarTabla(tbClienteCnsultas, "SELECT * FROM Clientes WHERE Telefono LIKE '" + txtClienteTelefono.getText() + "%'");

            }
        } else if (rbNegocio.isSelected()) {
            if (r.componentesVacios(txtClienteNegocio)) {
                r.mostrarNotificacionCuidado("Ne se pudo obtener ningun resultado", "Dbes ingresar datos al campo seleccionado para buscar al cliente....");
            } else {
                r.mostrarTabla(tbClienteCnsultas, "SELECT * FROM Clientes WHERE Negocio LIKE '" + txtClienteNegocio.getText() + "%'");

            }
        }
    }//GEN-LAST:event_btnClienteBuscarActionPerformed

    public void setColor(JPanel panel) {
        panel.setBackground(new java.awt.Color(197, 197, 197));
    }

    public void resetColor(JPanel panel) {
        panel.setBackground(new java.awt.Color(223, 223, 223));
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
 /*
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaClientesConsultas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.icm.components.metro.ButtonMetroICM btnCleinteLimpiar;
    private com.icm.components.metro.ButtonMetroICM btnClienteBuscar;
    private com.icm.components.metro.ButtonMetroICM btnClienteCancelar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel jpPrincipal;
    private com.icm.components.metro.RadioButtonMetroICM rbCurp;
    private com.icm.components.metro.RadioButtonMetroICM rbDireccion;
    private com.icm.components.metro.RadioButtonMetroICM rbNegocio;
    private com.icm.components.metro.RadioButtonMetroICM rbNombre;
    private com.icm.components.metro.RadioButtonMetroICM rbPrimerAp;
    private com.icm.components.metro.RadioButtonMetroICM rbSegundoAp;
    private com.icm.components.metro.RadioButtonMetroICM rbTelefono;
    private com.icm.components.metro.TableMetroICM tbClienteCnsultas;
    private com.icm.components.metro.TextFieldMetroICM txtClienteCurp;
    private com.icm.components.metro.TextFieldMetroICM txtClienteDireccion;
    private com.icm.components.metro.TextFieldMetroICM txtClienteNegocio;
    private com.icm.components.metro.TextFieldMetroICM txtClienteNombre;
    private com.icm.components.metro.TextFieldMetroICM txtClientePrimerAp;
    private com.icm.components.metro.TextFieldMetroICM txtClienteSegundoAp;
    private com.icm.components.metro.TextFieldMetroICM txtClienteTelefono;
    // End of variables declaration//GEN-END:variables
}
