/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista.proveedor;

import static vista.clientes.VariablesCliente.r;
import java.awt.Component;
import java.awt.FocusTraversalPolicy;
import javax.swing.JPanel;

/**
 *
 * @author liza
 */
public class VentanaProveedoresConsultas extends javax.swing.JFrame {

    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaProveedoresConsultas() {
        initComponents();
        setLocationRelativeTo(null);
        r.mostrarTabla(tbProveedorConsultas, "SELECT * FROM Proveedores");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jpPrincipal = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtProveedorRfc = new com.icm.components.metro.TextFieldMetroICM();
        txtProveedorNombre = new com.icm.components.metro.TextFieldMetroICM();
        txtProveedorSegundoAp = new com.icm.components.metro.TextFieldMetroICM();
        txtProveedorPrimerAp = new com.icm.components.metro.TextFieldMetroICM();
        txtProveedorEmpresa = new com.icm.components.metro.TextFieldMetroICM();
        txtProveedorTelefono = new com.icm.components.metro.TextFieldMetroICM();
        txtProveedorDireccion = new com.icm.components.metro.TextFieldMetroICM();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        btnProveedorBuscar = new com.icm.components.metro.ButtonMetroICM();
        btnProveedorLimpiar = new com.icm.components.metro.ButtonMetroICM();
        btnProveedorCancelar = new com.icm.components.metro.ButtonMetroICM();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbProveedorConsultas = new com.icm.components.metro.TableMetroICM();
        jPanel3 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        rbRfc = new com.icm.components.metro.RadioButtonMetroICM();
        rbNombre = new com.icm.components.metro.RadioButtonMetroICM();
        rbPrimerAp = new com.icm.components.metro.RadioButtonMetroICM();
        rbSegundoAp = new com.icm.components.metro.RadioButtonMetroICM();
        rbDireccion = new com.icm.components.metro.RadioButtonMetroICM();
        rbTelefono = new com.icm.components.metro.RadioButtonMetroICM();
        rbEmpresa = new com.icm.components.metro.RadioButtonMetroICM();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Proveedores Consultas");
        setSize(new java.awt.Dimension(860, 600));

        jpPrincipal.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(31, 189, 190));

        jPanel4.setBackground(new java.awt.Color(31, 189, 190));
        jPanel4.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 221, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 104, Short.MAX_VALUE)
        );

        jPanel5.setBackground(new java.awt.Color(31, 189, 190));
        jPanel5.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 109, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jLabel2.setFont(new java.awt.Font("Verdana", 1, 36)); // NOI18N
        jLabel2.setForeground(java.awt.Color.white);
        jLabel2.setText("Proveedores Consultas");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(90, 90, 90)
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel1.setText("Ingresa los siguientes datos:");

        jLabel3.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel3.setText("Rfc:");

        txtProveedorRfc.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(216, 0, 115)));
        txtProveedorRfc.setToolTipText("");
        txtProveedorRfc.setDark(false);
        txtProveedorRfc.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        txtProveedorRfc.setMaximumSize(new java.awt.Dimension(300, 48));
        txtProveedorRfc.setNextFocusableComponent(txtProveedorNombre);
        txtProveedorRfc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtProveedorRfcKeyReleased(evt);
            }
        });

        txtProveedorNombre.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(216, 0, 115)));
        txtProveedorNombre.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        txtProveedorNombre.setMaximumSize(new java.awt.Dimension(300, 48));
        txtProveedorNombre.setNextFocusableComponent(txtProveedorPrimerAp);
        txtProveedorNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtProveedorNombreActionPerformed(evt);
            }
        });
        txtProveedorNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtProveedorNombreKeyReleased(evt);
            }
        });

        txtProveedorSegundoAp.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(216, 0, 115)));
        txtProveedorSegundoAp.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        txtProveedorSegundoAp.setMaximumSize(new java.awt.Dimension(300, 48));
        txtProveedorSegundoAp.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtProveedorSegundoApKeyReleased(evt);
            }
        });

        txtProveedorPrimerAp.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(216, 0, 115)));
        txtProveedorPrimerAp.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        txtProveedorPrimerAp.setMaximumSize(new java.awt.Dimension(300, 48));
        txtProveedorPrimerAp.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtProveedorPrimerApKeyReleased(evt);
            }
        });

        txtProveedorEmpresa.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(216, 0, 115)));
        txtProveedorEmpresa.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        txtProveedorEmpresa.setMaximumSize(new java.awt.Dimension(300, 48));
        txtProveedorEmpresa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtProveedorEmpresaKeyReleased(evt);
            }
        });

        txtProveedorTelefono.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(216, 0, 115)));
        txtProveedorTelefono.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        txtProveedorTelefono.setMaximumSize(new java.awt.Dimension(300, 48));
        txtProveedorTelefono.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtProveedorTelefonoKeyReleased(evt);
            }
        });

        txtProveedorDireccion.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(216, 0, 115)));
        txtProveedorDireccion.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        txtProveedorDireccion.setMaximumSize(new java.awt.Dimension(300, 48));
        txtProveedorDireccion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtProveedorDireccionKeyReleased(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel4.setText("Nombre:");

        jLabel5.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel5.setText("Primer apellido:");

        jLabel6.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel6.setText("Segundo apellido:");

        jLabel7.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel7.setText("Dirección:");

        jLabel8.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel8.setText("Teléfono:");

        jLabel9.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel9.setText("Nombre empresa:");

        btnProveedorBuscar.setBackground(new java.awt.Color(31, 189, 190));
        btnProveedorBuscar.setText("Buscar");
        btnProveedorBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProveedorBuscarActionPerformed(evt);
            }
        });

        btnProveedorLimpiar.setBackground(new java.awt.Color(96, 169, 23));
        btnProveedorLimpiar.setText("Limpiar");
        btnProveedorLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProveedorLimpiarActionPerformed(evt);
            }
        });

        btnProveedorCancelar.setBackground(new java.awt.Color(206, 53, 44));
        btnProveedorCancelar.setText("Cancelar");
        btnProveedorCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProveedorCancelarActionPerformed(evt);
            }
        });

        tbProveedorConsultas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tbProveedorConsultas);

        jPanel3.setBackground(java.awt.Color.white);

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/BUscar.png"))); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel10)
                .addGap(45, 45, 45))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addComponent(jLabel10)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel11.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel11.setText("Proveedores:");

        buttonGroup1.add(rbRfc);
        rbRfc.setDark(false);
        rbRfc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbRfcActionPerformed(evt);
            }
        });

        buttonGroup1.add(rbNombre);
        rbNombre.setDark(false);
        rbNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbNombreActionPerformed(evt);
            }
        });

        buttonGroup1.add(rbPrimerAp);
        rbPrimerAp.setDark(false);
        rbPrimerAp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbPrimerApActionPerformed(evt);
            }
        });

        buttonGroup1.add(rbSegundoAp);
        rbSegundoAp.setDark(false);
        rbSegundoAp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbSegundoApActionPerformed(evt);
            }
        });

        buttonGroup1.add(rbDireccion);
        rbDireccion.setDark(false);
        rbDireccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbDireccionActionPerformed(evt);
            }
        });

        buttonGroup1.add(rbTelefono);
        rbTelefono.setDark(false);
        rbTelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbTelefonoActionPerformed(evt);
            }
        });

        buttonGroup1.add(rbEmpresa);
        rbEmpresa.setDark(false);
        rbEmpresa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbEmpresaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpPrincipalLayout = new javax.swing.GroupLayout(jpPrincipal);
        jpPrincipal.setLayout(jpPrincipalLayout);
        jpPrincipalLayout.setHorizontalGroup(
            jpPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jpPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpPrincipalLayout.createSequentialGroup()
                        .addGroup(jpPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpPrincipalLayout.createSequentialGroup()
                                .addGap(35, 35, 35)
                                .addComponent(jLabel1))
                            .addGroup(jpPrincipalLayout.createSequentialGroup()
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jpPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(rbRfc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(rbNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(rbPrimerAp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(rbSegundoAp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(rbDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(rbTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(rbEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(18, 18, 18)
                        .addGroup(jpPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addGroup(jpPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel5)))
                        .addGap(18, 18, 18)
                        .addGroup(jpPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtProveedorEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                            .addComponent(txtProveedorTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                            .addComponent(txtProveedorDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                            .addComponent(txtProveedorSegundoAp, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                            .addComponent(txtProveedorPrimerAp, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                            .addComponent(txtProveedorNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                            .addComponent(txtProveedorRfc, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE))
                        .addGap(64, 64, 64)
                        .addGroup(jpPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnProveedorBuscar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnProveedorLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnProveedorCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(71, 71, 71))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpPrincipalLayout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addContainerGap())
                    .addGroup(jpPrincipalLayout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jpPrincipalLayout.setVerticalGroup(
            jpPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpPrincipalLayout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpPrincipalLayout.createSequentialGroup()
                        .addGroup(jpPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtProveedorRfc, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel3))
                            .addComponent(rbRfc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jpPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpPrincipalLayout.createSequentialGroup()
                                .addGroup(jpPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jpPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(txtProveedorNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel4))
                                    .addComponent(rbNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jpPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jpPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(txtProveedorPrimerAp, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel5))
                                    .addComponent(rbPrimerAp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jpPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jpPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(txtProveedorSegundoAp, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel6))
                                    .addComponent(rbSegundoAp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jpPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jpPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(txtProveedorDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel7))
                                    .addComponent(rbDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jpPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(rbTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jpPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(txtProveedorTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel8))))
                            .addGroup(jpPrincipalLayout.createSequentialGroup()
                                .addComponent(btnProveedorBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(56, 56, 56)
                                .addComponent(btnProveedorLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(56, 56, 56)
                                .addComponent(btnProveedorCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jpPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rbEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jpPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtProveedorEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel9))))
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel11)
                .addGap(3, 3, 3)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 177, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rbRfcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbRfcActionPerformed
        // TODO add your handling code here:
        r.mostrarTabla(tbProveedorConsultas, "SELECT * FROM Proveedores");
        r.seleccionRBBuscar(txtProveedorRfc, txtProveedorNombre, txtProveedorPrimerAp, txtProveedorSegundoAp, txtProveedorDireccion, txtProveedorTelefono, txtProveedorEmpresa);
    }//GEN-LAST:event_rbRfcActionPerformed

    private void rbNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbNombreActionPerformed
        // TODO add your handling code here:
        r.mostrarTabla(tbProveedorConsultas, "SELECT * FROM Proveedores");
        r.seleccionRBBuscar(txtProveedorNombre, txtProveedorRfc, txtProveedorPrimerAp, txtProveedorSegundoAp, txtProveedorDireccion, txtProveedorTelefono, txtProveedorEmpresa);

    }//GEN-LAST:event_rbNombreActionPerformed

    private void rbPrimerApActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbPrimerApActionPerformed
        // TODO add your handling code here:
        r.mostrarTabla(tbProveedorConsultas, "SELECT * FROM Proveedores");
        r.seleccionRBBuscar(txtProveedorPrimerAp, txtProveedorNombre, txtProveedorRfc, txtProveedorSegundoAp, txtProveedorDireccion, txtProveedorTelefono, txtProveedorEmpresa);

    }//GEN-LAST:event_rbPrimerApActionPerformed

    private void rbSegundoApActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbSegundoApActionPerformed
        // TODO add your handling code here:
        r.mostrarTabla(tbProveedorConsultas, "SELECT * FROM Proveedores");
        r.seleccionRBBuscar(txtProveedorSegundoAp, txtProveedorPrimerAp, txtProveedorNombre, txtProveedorRfc, txtProveedorDireccion, txtProveedorTelefono, txtProveedorEmpresa);

    }//GEN-LAST:event_rbSegundoApActionPerformed

    private void rbDireccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbDireccionActionPerformed
        // TODO add your handling code here:
        r.mostrarTabla(tbProveedorConsultas, "SELECT * FROM Proveedores");
        r.seleccionRBBuscar(txtProveedorDireccion, txtProveedorSegundoAp, txtProveedorPrimerAp, txtProveedorNombre, txtProveedorRfc, txtProveedorTelefono, txtProveedorEmpresa);

    }//GEN-LAST:event_rbDireccionActionPerformed

    private void rbTelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbTelefonoActionPerformed
        // TODO add your handling code here:
        r.mostrarTabla(tbProveedorConsultas, "SELECT * FROM Proveedores");
        r.seleccionRBBuscar(txtProveedorTelefono, txtProveedorDireccion, txtProveedorSegundoAp, txtProveedorPrimerAp, txtProveedorNombre, txtProveedorRfc, txtProveedorEmpresa);

    }//GEN-LAST:event_rbTelefonoActionPerformed

    private void rbEmpresaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbEmpresaActionPerformed
        // TODO add your handling code here:
        r.mostrarTabla(tbProveedorConsultas, "SELECT * FROM Proveedores");
        r.seleccionRBBuscar(txtProveedorEmpresa, txtProveedorTelefono, txtProveedorDireccion, txtProveedorSegundoAp, txtProveedorPrimerAp, txtProveedorNombre, txtProveedorRfc);

    }//GEN-LAST:event_rbEmpresaActionPerformed

    private void btnProveedorCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProveedorCancelarActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnProveedorCancelarActionPerformed

    private void txtProveedorRfcKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtProveedorRfcKeyReleased
        // TODO add your handling code here:
        r.mostrarTabla(tbProveedorConsultas, "SELECT * FROM Proveedores WHERE Rfc LIKE '" + txtProveedorRfc.getText().toUpperCase() + "%'");
    }//GEN-LAST:event_txtProveedorRfcKeyReleased

    private void txtProveedorNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtProveedorNombreActionPerformed
        // TODO add your handling code here:
        r.mostrarTabla(tbProveedorConsultas, "SELECT * FROM Proveedores WHERE Nombre LIKE '" + txtProveedorNombre.getText() + "%'");
    }//GEN-LAST:event_txtProveedorNombreActionPerformed

    private void txtProveedorPrimerApKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtProveedorPrimerApKeyReleased
        // TODO add your handling code here:
        r.mostrarTabla(tbProveedorConsultas, "SELECT * FROM Proveedores WHERE Primer_Ap LIKE '" + txtProveedorPrimerAp.getText() + "%'");
    }//GEN-LAST:event_txtProveedorPrimerApKeyReleased

    private void txtProveedorSegundoApKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtProveedorSegundoApKeyReleased
        // TODO add your handling code here:
        r.mostrarTabla(tbProveedorConsultas, "SELECT * FROM Proveedores WHERE Segundo_Ap LIKE '" + txtProveedorSegundoAp.getText() + "%'");

    }//GEN-LAST:event_txtProveedorSegundoApKeyReleased

    private void txtProveedorDireccionKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtProveedorDireccionKeyReleased
        // TODO add your handling code here:
        r.mostrarTabla(tbProveedorConsultas, "SELECT * FROM Proveedores WHERE Direccion LIKE '" + txtProveedorDireccion.getText() + "%'");
    }//GEN-LAST:event_txtProveedorDireccionKeyReleased

    private void txtProveedorTelefonoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtProveedorTelefonoKeyReleased
        // TODO add your handling code here:
        r.mostrarTabla(tbProveedorConsultas, "SELECT * FROM Proveedores WHERE Telefono LIKE '" + txtProveedorTelefono.getText() + "%'");
    }//GEN-LAST:event_txtProveedorTelefonoKeyReleased

    private void txtProveedorEmpresaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtProveedorEmpresaKeyReleased
        // TODO add your handling code here:
        r.mostrarTabla(tbProveedorConsultas, "SELECT * FROM Proveedores WHERE Empresa LIKE '" + txtProveedorEmpresa.getText() + "%'");

    }//GEN-LAST:event_txtProveedorEmpresaKeyReleased

    private void txtProveedorNombreKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtProveedorNombreKeyReleased
        // TODO add your handling code here:
        r.mostrarTabla(tbProveedorConsultas, "SELECT * FROM Proveedores WHERE Nombre LIKE '" + txtProveedorNombre.getText() + "%'");

    }//GEN-LAST:event_txtProveedorNombreKeyReleased

    private void btnProveedorBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProveedorBuscarActionPerformed
        // TODO add your handling code here:
        if (rbRfc.isSelected()) {
            r.seleccionRBBuscar(txtProveedorRfc, txtProveedorNombre, txtProveedorPrimerAp, txtProveedorSegundoAp, txtProveedorDireccion, txtProveedorTelefono, txtProveedorEmpresa);

        } else if (rbNombre.isSelected()) {
            r.seleccionRBBuscar(txtProveedorNombre, txtProveedorRfc, txtProveedorPrimerAp, txtProveedorSegundoAp, txtProveedorDireccion, txtProveedorTelefono, txtProveedorEmpresa);

        } else if (rbPrimerAp.isSelected()) {
            r.mostrarTabla(tbProveedorConsultas, "SELECT * FROM Proveedores WHERE Primer_Ap LIKE '" + txtProveedorPrimerAp.getText() + "%'");

        } else if (rbSegundoAp.isSelected()) {
            r.mostrarTabla(tbProveedorConsultas, "SELECT * FROM Proveedores WHERE Segundo_Ap LIKE '" + txtProveedorSegundoAp.getText() + "%'");

        } else if (rbDireccion.isSelected()) {
            r.mostrarTabla(tbProveedorConsultas, "SELECT * FROM Proveedores WHERE Direccion LIKE '" + txtProveedorDireccion.getText() + "%'");

        } else if (rbTelefono.isSelected()) {
            r.mostrarTabla(tbProveedorConsultas, "SELECT * FROM Proveedores WHERE Telefono LIKE '" + txtProveedorTelefono.getText() + "%'");

        } else if (rbEmpresa.isSelected()) {
            r.mostrarTabla(tbProveedorConsultas, "SELECT * FROM Proveedores WHERE Empresa LIKE '" + txtProveedorEmpresa.getText() + "%'");

        }
    }//GEN-LAST:event_btnProveedorBuscarActionPerformed

    private void btnProveedorLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProveedorLimpiarActionPerformed
        // TODO add your handling code here:
        r.limpiar(txtProveedorRfc, txtProveedorNombre, txtProveedorPrimerAp, txtProveedorSegundoAp, txtProveedorDireccion, txtProveedorEmpresa, txtProveedorTelefono);
        buttonGroup1.clearSelection();
        r.habilitarComponentes(false,txtProveedorRfc, txtProveedorNombre, txtProveedorPrimerAp, txtProveedorSegundoAp, txtProveedorDireccion, txtProveedorEmpresa, txtProveedorTelefono);
         r.mostrarTabla(tbProveedorConsultas, "SELECT * FROM Proveedores");
    }//GEN-LAST:event_btnProveedorLimpiarActionPerformed

    public void setColor(JPanel panel) {
        panel.setBackground(new java.awt.Color(197, 197, 197));
    }

    public void resetColor(JPanel panel) {
        panel.setBackground(new java.awt.Color(223, 223, 223));
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
 /*
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaProveedoresConsultas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.icm.components.metro.ButtonMetroICM btnProveedorBuscar;
    private com.icm.components.metro.ButtonMetroICM btnProveedorCancelar;
    private com.icm.components.metro.ButtonMetroICM btnProveedorLimpiar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel jpPrincipal;
    private com.icm.components.metro.RadioButtonMetroICM rbDireccion;
    private com.icm.components.metro.RadioButtonMetroICM rbEmpresa;
    private com.icm.components.metro.RadioButtonMetroICM rbNombre;
    private com.icm.components.metro.RadioButtonMetroICM rbPrimerAp;
    private com.icm.components.metro.RadioButtonMetroICM rbRfc;
    private com.icm.components.metro.RadioButtonMetroICM rbSegundoAp;
    private com.icm.components.metro.RadioButtonMetroICM rbTelefono;
    private com.icm.components.metro.TableMetroICM tbProveedorConsultas;
    private com.icm.components.metro.TextFieldMetroICM txtProveedorDireccion;
    private com.icm.components.metro.TextFieldMetroICM txtProveedorEmpresa;
    private com.icm.components.metro.TextFieldMetroICM txtProveedorNombre;
    private com.icm.components.metro.TextFieldMetroICM txtProveedorPrimerAp;
    private com.icm.components.metro.TextFieldMetroICM txtProveedorRfc;
    private com.icm.components.metro.TextFieldMetroICM txtProveedorSegundoAp;
    private com.icm.components.metro.TextFieldMetroICM txtProveedorTelefono;
    // End of variables declaration//GEN-END:variables
}
